# Generated by Django 5.1.1 on 2024-09-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cbd_end_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cbd_start_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_end_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_start_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='thc_end_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='thc_start_range',
            field=models.FloatField(),
        ),
    ]
